// CSV/Excel-compatible task import template helpers
export interface ExcelTaskRow { rowNumber: number; projectName?: string; projectId?: string; taskName?: string; description?: string; assignedTo?: string; assignees?: string; dependencies?: string; startDate?: string; endDate?: string; dueDate?: string; status?: string; priority?: string; remarks?: string; notes?: string; links?: string; subtaskName?: string; subtaskDescription?: string; subtaskStatus?: string; subtaskAssignedTo?: string; subtaskStartDate?: string; subtaskDueDate?: string }

export function generateSampleExcel(): string {
  const headers = ["Project Name", "Task Name", "Description", "Assigned To", "Dependencies (Task IDs, comma-separated)", "Start Date", "End Date", "Status", "Priority", "Subtask Name", "Subtask Description", "Subtask Status", "Subtask Assigned To", "Subtask Start Date", "Subtask Due Date"]
  const rows = [["Website Redesign", "Homepage Design", "Create homepage mockup", "Akshay Singh", "", "2026-04-01", "2026-04-15", "in-progress", "high", "Create wireframes", "Prepare responsive wireframes", "todo", "Akshay Singh", "2026-04-01", "2026-04-05"], ["Website Redesign", "Homepage Design", "Create homepage mockup", "Akshay Singh", "", "2026-04-01", "2026-04-15", "in-progress", "high", "Review design", "Stakeholder review", "todo", "Akshay Singh", "2026-04-06", "2026-04-08"]]
  return [headers, ...rows].map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\n") + "\n"
}
export function downloadSampleExcel(): void { const blob = new Blob([generateSampleExcel()], { type: "text/csv;charset=utf-8;" }); const link = document.createElement("a"); const url = URL.createObjectURL(blob); link.href = url; link.download = "project-dashboard-task-subtasks-template.csv"; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url) }
export function parseCSV(content: string): ExcelTaskRow[] { const lines = content.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); if (lines.length < 2) return []; const headers = parseCSVLine(lines[0]).map(normalizeHeader); return lines.slice(1).map((line, index) => { const values = parseCSVLine(line); const row: ExcelTaskRow = { rowNumber: index + 2 }; headers.forEach((header, column) => { const value = (values[column] ?? "").trim(); if (value) (row as Record<string, unknown>)[header] = value }); return row }) }
function parseCSVLine(line: string): string[] { const result: string[] = []; let current = ""; let quoted = false; for (let index = 0; index < line.length; index++) { const char = line[index]; const next = line[index + 1]; if (char === '"') { if (quoted && next === '"') { current += '"'; index++ } else quoted = !quoted } else if (char === "," && !quoted) { result.push(current); current = "" } else current += char } result.push(current); return result }
function normalizeHeader(header: string): string { const key = header.trim().toLowerCase().replace(/[_-]+/g, " ").replace(/\s+/g, " "); const aliases: Record<string, string> = { "project name": "projectName", project: "projectName", "project id": "projectId", "task name": "taskName", task: "taskName", title: "taskName", description: "description", "assigned to": "assignedTo", assignee: "assignees", assignees: "assignees", dependencies: "dependencies", "start date": "startDate", "end date": "endDate", "due date": "dueDate", status: "status", priority: "priority", remarks: "remarks", notes: "notes", links: "links", "subtask name": "subtaskName", subtask: "subtaskName", "subtask description": "subtaskDescription", "subtask status": "subtaskStatus", "subtask assigned to": "subtaskAssignedTo", "subtask start date": "subtaskStartDate", "subtask due date": "subtaskDueDate" }; return aliases[key] ?? key }
